---
title: "Score Adjustments"
author: "Andrew McKinney"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

# load relevant libraries
library(tidyverse)
library(lubridate)
library(janitor)
library(tidymodels)

# get rid of scientific notation
options(scipen = 999)

# increase memory limit
memory.limit(size = 56000)

memory.limit()

```

```{r}

# load the data
raw_scores <- read_csv("C:/Users/andrew.mckinney/Dropbox/Projects/Golf/Cleaning/raw_scores.csv")

```

```{r}

# create the tournament-round interaction term
df_01 <-
  raw_scores %>%
  select(event_id, event, round, date, player, score) %>%
  mutate(tournament_round_interaction = paste0(event_id, "_", "R", round))

# filter data to 2-year windows
df_02_2021 <-
  df_01 %>%
  filter(year(date) == 2020 | year(date) == 2021)

df_02_1819 <-
  df_01 %>%
  filter(year(date) == 2018 | year(date) == 2019)

df_02_1617 <-
  df_01 %>%
  filter(year(date) == 2016 | year(date) == 2017)

df_02_1415 <-
  df_01 %>%
  filter(year(date) == 2014 | year(date) == 2015)

df_02_1213 <-
  df_01 %>%
  filter(year(date) == 2012 | year(date) == 2013)

df_02_1011 <-
  df_01 %>%
  filter(year(date) == 2010 | year(date) == 2011)

```

```{r}

# set seed
set.seed(101)

# specify fixed effects regression models
mod_2021 <- lm(score ~ 0 + player + tournament_round_interaction, data = df_02_2021)
mod_1819 <- lm(score ~ 0 + player + tournament_round_interaction, data = df_02_1819)
mod_1617 <- lm(score ~ 0 + player + tournament_round_interaction, data = df_02_1617)
mod_1415 <- lm(score ~ 0 + player + tournament_round_interaction, data = df_02_1415)
mod_1213 <- lm(score ~ 0 + player + tournament_round_interaction, data = df_02_1213)
mod_1011 <- lm(score ~ 0 + player + tournament_round_interaction, data = df_02_1011)

# tidy the results
df_03 <- 
  bind_rows(
    tidy(mod_2021),
    tidy(mod_1819),
    tidy(mod_1617),
    tidy(mod_1415),
    tidy(mod_1213),
    tidy(mod_1011)
  )

```

```{r}

# collect tournament-round terms
df_04 <-
  df_03 %>%
  filter(str_detect(term, "tournament_round")) %>%
  mutate(term = str_remove(term, "tournament_round_interaction")) %>%
  separate(
    term,
    into = c("event_id", "round"),
    sep = "_"
  ) %>%
  mutate(
    event_id = as.numeric(event_id),
    round = str_extract(round, "[:digit:]+") %>% as.numeric()
  ) %>%
  mutate_at(c("estimate", "std.error", "statistic", "p.value"), round, 5)

# add event name and date back to the tournament-round terms
df_05 <-
  df_01 %>%
  # to coincide with the 2-year window ending in 2021
  filter(year(date) <= 2021) %>%
  distinct(event_id, event, round, date) %>%
  left_join(., df_04 %>% select(event_id, round, estimate), by = c("event_id", "round")) %>%
  mutate(estimate = ifelse(is.na(estimate), 0, estimate))

# save the tournament-round terms
write_csv(df_05, "tournament_round_terms.csv")

```

```{r}

# adjusted scores
df_06 <- 
  df_01 %>%
  # to coincide with the 2-year window ending in 2021
  filter(year(date) <= 2021) %>%
  select(event_id, event, round, date, player, raw_score = score) %>%
  left_join(., df_05, by = c("event_id", "event", "round", "date")) %>%
  rename(tournament_round_adjustment = estimate) %>%
  mutate(adjusted_score = raw_score - tournament_round_adjustment)

# save adjusted scores
write_csv(df_06, "adjusted_scores_2010_2021.csv")

```

